version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bank
      MARIADB_USER: bank_owner
      MARIADB_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
